### ISSUE TITLE
Cannot uninstall FakerInput, system essentially bricked

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/FakerInput#1]
I have been trying to uninstall Fakerinput for a while now, and yesterday tried to enter safe mode and forcefully uninstall the HID drivers under FakerInput from device manager, since the uninstaller ends prematurely every time and does not accomplish anything.

When removing the drivers some of them didnt, and stayed after reboot, so for my last attempt tried in safe mode, waited 5 minutes and checked again the ones that didn't uninstall the first time.

After reboot keyboards and mice don't respond. They get recognized and windows emits the plug/unplug sound, any other new device I connect gets its drivers fetched and installed, but HID DOES NOT WORK, EVEN IN SAFE MODE.

I did make sure to only uninstall drivers signed by you and under FakerInput container.

Tried to enter safe mode with command prompt, that way HID works, and used pnputil -e, pnputil -d as a last attempt to get the drivers out. No such luck.

Any suggestions?

**Comment by Ryochan7** [comment]
The uninstaller has worked for me on my main Windows 10 install and my Windows 10 VM. The first option for possibly debugging the uninstaller is to run msiexec manually from cmd or PowerShell and enable logging messages; make sure to run PowerShell as the admin and run msiexec from a directory you have write access to.

```
msiexec -x FakerInput_0.1.0_x64.msi -l*v Log.txt
```

If attempting to remove the driver manually, I am pretty sure you have to delete the assocaited HID Keyboard device in Device Manager first before doing anything else; the uninstall portion performs that step first. Check under Keyboards > HID Keyboard Device. Open the Properties window for the device and find the one with the Location listed as `on FakerInput Device`.

You can then remove the system device from System devices > FakerInput Device. Make sure to select the option to uninstall the driver as well as removing the device. Removing that device should get rid of all the extra HID devices associated with the driver. If you don't choose the uninstall driver option, I would suggest that you check out the app Driver Store Explorer. I use the app regularly for removing drivers.

https://github.com/lostindark/DriverStoreExplorer

**Comment by alpharou** [comment]
I cannot run the uninstaller now, since keyboard and mice dont work

**Comment by Ryochan7** [comment]
Can you access System Restore from Windows Recovery Mode? That would be independent of your current borked Windows install. Hopefully you have a recent restore point you can go back to so you can avoid a full re-install of Windows.

**Comment by alpharou** [comment]
Had to reinstall from USB, driver kept messing even after windows reset and reinstall (without cleaning all the files).

That was really bad IMO, keep an eye on it or try with other systems if possible
